apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-disease-api-deployment
  labels:
    app: heart-disease-api
spec:
  replicas: 2  # High availability: 2 instances of your API
  selector:
    matchLabels:
      app: heart-disease-api
  template:
    metadata:
      labels:
        app: heart-disease-api
    spec:
      containers:
      - name: heart-disease-api
        image: heart-disease-api:latest  # The tag from your local docker build
        imagePullPolicy: Never           # Tells K8s to look for the local image
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: heart-disease-service
spec:
  type: LoadBalancer  # Docker Desktop will map this to localhost
  selector:
    app: heart-disease-api
  ports:
    - protocol: TCP
      port: 80        # Port exposed to your browser
      targetPort: 8000 # Port inside the container